name: Deploy to Firebase on merge
on:
  push:
    branches:
      - prod
      - staging

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn install
      - run: yarn functions:build
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ github.ref_name == 'prod' && secrets.FIREBASE_SERVICE_ACCOUNT_IPLANX_BB47F || secrets.FIREBASE_SERVICE_ACCOUNT_IPLANX_STAGING }}
      - name: Deploy to Firebase (Functions & Hosting)
        run: |
          npx firebase deploy --only functions,hosting:${{ github.ref_name == 'prod' && 'ilinkx' || 'iurlx-staging' }} --project ${{ github.ref_name == 'prod' && 'iplanx-bb47f' || 'iplanx-staging' }} --non-interactive
